"""Small Windows launcher for validated YAML simulation cases."""

from __future__ import annotations

import copy
import hashlib
import json
import os
import queue
import re
import subprocess
import sys
import threading
import time
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
import tkinter as tk
from tkinter import messagebox, ttk

import yaml
from pydantic import ValidationError

LAUNCHER_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = LAUNCHER_DIR.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from batch_runner.config import CaseConfig, resolve_case
from launcher_diagnosis import (
    PREFLIGHT_PREFIX,
    format_preflight_diagnosis,
    write_run_diagnosis,
)


CASES_DIR = PROJECT_ROOT / "cases"
RUNS_DIR = PROJECT_ROOT / "runs"
TEMPLATE_NAME = "schema_template.yaml"


@dataclass(frozen=True)
class RunSnapshot:
    run_dir: Path
    config_path: Path
    results_dir: Path


def read_case_mapping(path: Path) -> dict:
    with path.open(encoding="utf-8") as stream:
        raw = yaml.safe_load(stream)
    if not isinstance(raw, dict):
        raise ValueError(f"case config must contain a YAML mapping: {path}")
    return raw


def validate_case_file(path: Path) -> CaseConfig:
    """Validate schema, combinations, time preprocessing, and input paths."""
    raw = read_case_mapping(path)
    config = CaseConfig.model_validate(raw)
    validation_raw = copy.deepcopy(raw)
    validation_raw["paths"]["output_dir"] = str(
        RUNS_DIR / ".validation" / f"{_safe_name(config.case.name)}-{time.time_ns()}" / "results"
    )
    resolve_case(CaseConfig.model_validate(validation_raw), path.resolve())
    return config


def preflight_case_file(path: Path) -> dict:
    command = [
        sys.executable,
        "-X",
        "faulthandler",
        str(PROJECT_ROOT / "runner.py"),
        "--preflight",
        str(path),
    ]
    completed = subprocess.run(
        command,
        cwd=PROJECT_ROOT,
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
        creationflags=subprocess.CREATE_NO_WINDOW if os.name == "nt" else 0,
    )
    for line in reversed(completed.stdout.splitlines()):
        if line.startswith(PREFLIGHT_PREFIX):
            report = json.loads(line[len(PREFLIGHT_PREFIX) :])
            report["process_return_code"] = completed.returncode
            if report.get("ready") and completed.returncode != 0:
                report.update(
                    {
                        "ready": False,
                        "failed_stage": "preflight_process",
                        "exception_type": "ChildProcessError",
                        "error_message": f"preflight checks passed but the process exited with code {completed.returncode}",
                        "technical_traceback": completed.stderr or report.get("technical_traceback"),
                    }
                )
            return report
    output = "\n".join(part for part in (completed.stdout, completed.stderr) if part).strip()
    return {
        "ready": False,
        "case_name": None,
        "failed_stage": "preflight_process",
        "exception_type": "ChildProcessError",
        "error_message": f"preflight process exited with code {completed.returncode} without a report",
        "kinetic_mapping": [],
        "technical_traceback": output or None,
        "process_return_code": completed.returncode,
    }


def create_run_snapshot(
    case_path: Path,
    *,
    runs_dir: Path = RUNS_DIR,
    now: datetime | None = None,
) -> RunSnapshot:
    """Create a traceable run YAML, changing only its fresh output path."""
    config = validate_case_file(case_path)
    timestamp = (now or datetime.now()).strftime("%Y-%m-%d_%H-%M-%S")
    base = runs_dir / _safe_name(config.case.name) / timestamp
    run_dir = base
    suffix = 2
    while run_dir.exists():
        run_dir = base.with_name(f"{base.name}_{suffix:02d}")
        suffix += 1
    run_dir.mkdir(parents=True)

    results_dir = run_dir / "results"
    raw = read_case_mapping(case_path)
    generated = copy.deepcopy(raw)
    try:
        output_path = results_dir.relative_to(PROJECT_ROOT).as_posix()
    except ValueError:
        output_path = str(results_dir.resolve())
    generated["paths"]["output_dir"] = output_path

    if _without_output_dir(generated) != _without_output_dir(raw):
        raise RuntimeError("run snapshot changed a setting other than paths.output_dir")

    source_path = _display_path(case_path)
    source_sha256 = _sha256(case_path)
    config_path = run_dir / "run_case.yaml"
    header = (
        "# Generated by the Reaktoro Simulation Launcher.\n"
        f"# Source case: {source_path}\n"
        f"# Source SHA256: {source_sha256}\n"
        "# Scientific settings are unchanged; only paths.output_dir is new.\n"
    )
    config_path.write_text(
        header + yaml.safe_dump(generated, sort_keys=False),
        encoding="utf-8",
    )
    return RunSnapshot(run_dir, config_path, results_dir)


def case_summary(path: Path) -> str:
    config = CaseConfig.model_validate(read_case_mapping(path))
    timestep = config.solver.timestep
    duration = f"{timestep.time.duration_value:g} {timestep.time.duration_unit}"
    if timestep.mode == "fixed":
        dt = timestep.step_size.dt
        step = f"{dt.value:g} {dt.unit}"
    else:
        size = timestep.step_size
        step = (
            f"initial {size.dt_initial.value:g} {size.dt_initial.unit}; "
            f"min {size.dt_min.value:g} {size.dt_min.unit}; "
            f"max {size.dt_max.value:g} {size.dt_max.unit}"
        )
    model = config.kinetics.model if config.kinetics.enabled else "equilibrium only"
    minerals = ", ".join(mineral.name for mineral in config.minerals)
    return "\n".join(
        [
            f"File: {_display_path(path)}",
            f"Case: {config.case.name}",
            f"Kinetic model: {model}",
            f"Minerals: {minerals}",
            f"Temperature: {config.physical.temperature_c:g} °C",
            f"Pressure: {config.physical.pressure_bar:g} bar",
            f"CO₂ mode: {config.co2.mode}",
            f"Workflow: {config.solver.workflow.mode}",
            f"Timestep mode: {timestep.mode}",
            f"Duration: {duration}",
            f"Step: {step}",
        ]
    )


def _without_output_dir(raw: dict) -> dict:
    scientific = copy.deepcopy(raw)
    scientific["paths"].pop("output_dir", None)
    return scientific


def _safe_name(value: str) -> str:
    return re.sub(r"[^A-Za-z0-9._-]+", "_", value).strip("._") or "case"


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _display_path(path: Path) -> str:
    try:
        return path.resolve().relative_to(PROJECT_ROOT).as_posix()
    except ValueError:
        return str(path.resolve())


class SimulationLauncher:
    def __init__(self, root: tk.Tk) -> None:
        self.root = root
        self.case_paths: list[Path] = []
        self.preflight_reports: dict[Path, dict] = {}
        self.events: queue.Queue[tuple] = queue.Queue()
        self.running = False
        self.current_case = ""
        self.started_at = 0.0
        self.last_run_dir: Path | None = None

        root.title("Reaktoro Simulation Launcher")
        root.geometry("1000x680")
        root.minsize(760, 540)
        root.columnconfigure(0, weight=1)
        root.rowconfigure(1, weight=1)
        root.rowconfigure(4, weight=1)
        root.protocol("WM_DELETE_WINDOW", self._close)

        ttk.Label(
            root,
            text="Reaktoro Simulation Launcher",
            font=("Segoe UI", 16, "bold"),
        ).grid(row=0, column=0, sticky="w", padx=14, pady=(12, 6))

        content = ttk.Panedwindow(root, orient=tk.HORIZONTAL)
        content.grid(row=1, column=0, sticky="nsew", padx=14)

        cases_frame = ttk.Labelframe(content, text="Simulation cases", padding=8)
        summary_frame = ttk.Labelframe(content, text="Selected-case summary", padding=8)
        content.add(cases_frame, weight=3)
        content.add(summary_frame, weight=5)

        cases_frame.columnconfigure(0, weight=1)
        cases_frame.rowconfigure(0, weight=1)
        self.case_list = tk.Listbox(
            cases_frame,
            selectmode=tk.EXTENDED,
            exportselection=False,
            font=("Segoe UI", 10),
            width=42,
        )
        case_scroll = ttk.Scrollbar(cases_frame, command=self.case_list.yview)
        self.case_list.configure(yscrollcommand=case_scroll.set)
        self.case_list.grid(row=0, column=0, sticky="nsew")
        case_scroll.grid(row=0, column=1, sticky="ns")
        self.case_list.bind("<<ListboxSelect>>", self._show_summary)

        summary_frame.columnconfigure(0, weight=1)
        summary_frame.rowconfigure(0, weight=1)
        self.summary = tk.Text(
            summary_frame,
            wrap=tk.WORD,
            font=("Segoe UI", 10),
            padx=8,
            pady=6,
            state=tk.DISABLED,
        )
        self.summary.grid(row=0, column=0, sticky="nsew")

        actions = ttk.Frame(root)
        actions.grid(row=2, column=0, sticky="ew", padx=14, pady=8)
        self.refresh_button = ttk.Button(actions, text="Refresh cases", command=self.refresh_cases)
        self.open_case_button = ttk.Button(actions, text="Open case file", command=self.open_case)
        self.validate_button = ttk.Button(actions, text="Validate", command=self.validate_selected)
        self.run_button = ttk.Button(
            actions,
            text="Run selected",
            command=self.run_selected,
            state=tk.DISABLED,
        )
        self.open_results_button = ttk.Button(
            actions,
            text="Open last run",
            command=self.open_last_run,
            state=tk.DISABLED,
        )
        self.open_diagnosis_button = ttk.Button(
            actions,
            text="Open diagnosis",
            command=self.open_diagnosis,
            state=tk.DISABLED,
        )
        for button in (
            self.refresh_button,
            self.open_case_button,
            self.validate_button,
            self.run_button,
            self.open_results_button,
            self.open_diagnosis_button,
        ):
            button.pack(side=tk.LEFT, padx=(0, 8))

        status_frame = ttk.Frame(root)
        status_frame.grid(row=3, column=0, sticky="ew", padx=14, pady=(0, 8))
        status_frame.columnconfigure(0, weight=1)
        self.status_text = tk.StringVar(value="Ready")
        ttk.Label(status_frame, textvariable=self.status_text).grid(row=0, column=0, sticky="w")
        self.progress = ttk.Progressbar(status_frame, mode="indeterminate", length=180)
        self.progress.grid(row=0, column=1, sticky="e")
        self.progress.grid_remove()

        log_frame = ttk.Labelframe(root, text="Run log", padding=8)
        log_frame.grid(row=4, column=0, sticky="nsew", padx=14, pady=(0, 14))
        log_frame.columnconfigure(0, weight=1)
        log_frame.rowconfigure(0, weight=1)
        self.log = tk.Text(log_frame, wrap=tk.WORD, height=10, font=("Consolas", 9), state=tk.DISABLED)
        log_scroll = ttk.Scrollbar(log_frame, command=self.log.yview)
        self.log.configure(yscrollcommand=log_scroll.set)
        self.log.grid(row=0, column=0, sticky="nsew")
        log_scroll.grid(row=0, column=1, sticky="ns")

        self.refresh_cases()
        root.after(100, self._drain_events)
        root.after(1000, self._update_elapsed)

    def refresh_cases(self) -> None:
        self.preflight_reports.clear()
        self.case_paths = sorted(
            path for path in CASES_DIR.glob("*.yaml") if path.name != TEMPLATE_NAME
        )
        self.case_list.delete(0, tk.END)
        for path in self.case_paths:
            try:
                CaseConfig.model_validate(read_case_mapping(path))
                label = f"NOT CHECKED: {path.stem}"
            except (OSError, ValueError, TypeError, yaml.YAMLError, ValidationError) as error:
                label = f"BLOCKED: {path.stem}"
                self.preflight_reports[path] = {
                    "ready": False,
                    "failed_stage": "configuration_validation",
                    "error_message": str(error),
                    "kinetic_mapping": [],
                    "technical_traceback": None,
                }
            self.case_list.insert(tk.END, label)
        if self.case_paths:
            self.case_list.selection_set(0)
            self._show_summary()
        else:
            self._set_summary("No YAML cases were found in the cases folder.")

    def _selected_paths(self) -> list[Path]:
        return [self.case_paths[index] for index in self.case_list.curselection()]

    def _show_summary(self, _event: object | None = None) -> None:
        selected = self._selected_paths()
        if not selected:
            self._set_summary("Select a case to inspect it.")
            self._update_run_button()
            return
        try:
            text = case_summary(selected[0])
        except (OSError, ValueError, TypeError, yaml.YAMLError, ValidationError) as error:
            text = f"INVALID CASE\n\n{type(error).__name__}: {error}"
        if len(selected) > 1:
            text += f"\n\nQueue selection: {len(selected)} cases"
        report = self.preflight_reports.get(selected[0])
        if report is not None:
            text += "\n\n" + format_preflight_diagnosis(selected[0], report)
        self._set_summary(text)
        self._update_run_button()

    def _set_summary(self, text: str) -> None:
        self.summary.configure(state=tk.NORMAL)
        self.summary.delete("1.0", tk.END)
        self.summary.insert(tk.END, text)
        self.summary.configure(state=tk.DISABLED)

    def open_case(self) -> None:
        selected = self._selected_paths()
        if not selected:
            messagebox.showinfo("Select a case", "Select one case first.")
            return
        self.preflight_reports.pop(selected[0], None)
        self._render_case_labels()
        self._show_summary()
        os.startfile(selected[0])

    def validate_selected(self) -> None:
        selected = self._selected_paths()
        if not selected:
            messagebox.showinfo("Select cases", "Select one or more cases first.")
            return
        reports = self._preflight_selected(selected)
        blocked = [
            format_preflight_diagnosis(path, report)
            for path, report in zip(selected, reports)
            if not report.get("ready")
        ]
        if blocked:
            messagebox.showerror("Preflight blocked", "\n\n".join(blocked))
        else:
            messagebox.showinfo(
                "Preflight passed",
                f"{len(selected)} selected case(s) passed full construction preflight. No solver was started.",
            )
            self.status_text.set(f"Preflight passed for {len(selected)} case(s)")

    def _preflight_selected(self, paths: list[Path]) -> list[dict]:
        reports = []
        self.status_text.set(f"Checking {len(paths)} selected case(s)")
        self.root.update_idletasks()
        for path in paths:
            try:
                report = preflight_case_file(path)
            except (OSError, ValueError, TypeError, yaml.YAMLError, ValidationError) as error:
                report = {
                    "ready": False,
                    "failed_stage": "configuration_validation",
                    "exception_type": type(error).__name__,
                    "error_message": str(error),
                    "kinetic_mapping": [],
                    "technical_traceback": None,
                }
            self.preflight_reports[path] = report
            reports.append(report)
            diagnosis = format_preflight_diagnosis(path, report)
            self._append_log(f"\n{diagnosis}\n")
            if report.get("technical_traceback"):
                self._append_log(f"Technical traceback:\n{report['technical_traceback']}\n")
        self._render_case_labels()
        self._show_summary()
        return reports

    def _render_case_labels(self) -> None:
        selected = set(self._selected_paths())
        self.case_list.delete(0, tk.END)
        for index, path in enumerate(self.case_paths):
            report = self.preflight_reports.get(path)
            if report and report.get("ready"):
                status = "READY"
            elif report:
                status = "BLOCKED"
            else:
                status = "NOT CHECKED"
            self.case_list.insert(tk.END, f"{status}: {path.stem}")
            if path in selected:
                self.case_list.selection_set(index)
        self._update_run_button()

    def _update_run_button(self) -> None:
        selected = self._selected_paths()
        ready = bool(selected) and all(
            self.preflight_reports.get(path, {}).get("ready") for path in selected
        )
        self.run_button.configure(state=tk.NORMAL if ready and not self.running else tk.DISABLED)

    def run_selected(self) -> None:
        selected = self._selected_paths()
        if not selected:
            messagebox.showinfo("Select cases", "Select one or more cases first.")
            return
        reports = self._preflight_selected(selected)
        blocked = [
            format_preflight_diagnosis(path, report)
            for path, report in zip(selected, reports)
            if not report.get("ready")
        ]
        if blocked:
            messagebox.showerror("Run blocked by preflight", "\n\n".join(blocked))
            return

        self.running = True
        self.started_at = time.monotonic()
        self._set_running_controls(True)
        self.progress.grid()
        self.progress.start(10)
        self._append_log(f"Queued {len(selected)} case(s).\n")
        threading.Thread(target=self._run_queue, args=(selected,), daemon=True).start()

    def _run_queue(self, paths: list[Path]) -> None:
        failures = 0
        for index, path in enumerate(paths, start=1):
            self.events.put(("start", index, len(paths), path.name))
            try:
                snapshot = create_run_snapshot(path)
                self.events.put(("snapshot", snapshot.run_dir))
                command = [
                    sys.executable,
                    "-X",
                    "faulthandler",
                    str(PROJECT_ROOT / "runner.py"),
                    str(snapshot.config_path),
                ]
                creationflags = subprocess.CREATE_NO_WINDOW if os.name == "nt" else 0
                with (snapshot.run_dir / "launch_log.txt").open("w", encoding="utf-8") as stream:
                    stream.write(f"Source case: {_display_path(path)}\n")
                    stream.write(f"Run config: {_display_path(snapshot.config_path)}\n\n")
                    process = subprocess.Popen(
                        command,
                        cwd=PROJECT_ROOT,
                        stdout=subprocess.PIPE,
                        stderr=subprocess.STDOUT,
                        text=True,
                        encoding="utf-8",
                        errors="replace",
                        creationflags=creationflags,
                    )
                    assert process.stdout is not None
                    for line in process.stdout:
                        stream.write(line)
                        stream.flush()
                        self.events.put(("log", line))
                    return_code = process.wait()
                    stream.write(f"\nChild process exit code: {return_code}\n")
                diagnosis_path, diagnosis = write_run_diagnosis(snapshot.run_dir, return_code)
                if return_code:
                    failures += 1
                self.events.put(
                    (
                        "done",
                        path.name,
                        return_code,
                        snapshot.run_dir,
                        diagnosis_path,
                        diagnosis.splitlines()[0],
                    )
                )
            except Exception as error:  # Report unexpected launcher-boundary errors without hiding them.
                failures += 1
                self.events.put(("error", path.name, type(error).__name__, str(error)))
        self.events.put(("queue_done", len(paths), failures))

    def _drain_events(self) -> None:
        while True:
            try:
                event = self.events.get_nowait()
            except queue.Empty:
                break
            kind = event[0]
            if kind == "start":
                _, index, total, name = event
                self.current_case = f"{index}/{total}: {name}"
                self.status_text.set(f"Running {self.current_case}")
                self._append_log(f"\nRunning {self.current_case}\n")
            elif kind == "snapshot":
                self.last_run_dir = event[1]
                self.open_results_button.configure(state=tk.NORMAL)
            elif kind == "log":
                self._append_log(event[1])
            elif kind == "done":
                _, name, return_code, run_dir, diagnosis_path, outcome = event
                self.last_run_dir = run_dir
                self.open_diagnosis_button.configure(state=tk.NORMAL)
                self._append_log(
                    f"{name}: {outcome} (exit {return_code}). Diagnosis: {diagnosis_path}\n"
                )
            elif kind == "error":
                _, name, error_type, message = event
                self._append_log(f"{name}: launcher error: {error_type}: {message}\n")
            elif kind == "queue_done":
                _, total, failures = event
                self.running = False
                self.current_case = ""
                self.progress.stop()
                self.progress.grid_remove()
                self._set_running_controls(False)
                completed = total - failures
                self.status_text.set(f"Queue finished: {completed} completed, {failures} failed")
                if failures:
                    messagebox.showwarning(
                        "Queue finished",
                        f"{completed} case(s) completed and {failures} failed. Inspect the run log and diagnostics.",
                    )
                else:
                    messagebox.showinfo("Queue finished", f"All {completed} case(s) completed.")
        self.root.after(100, self._drain_events)

    def _append_log(self, text: str) -> None:
        self.log.configure(state=tk.NORMAL)
        self.log.insert(tk.END, text)
        self.log.see(tk.END)
        self.log.configure(state=tk.DISABLED)

    def _set_running_controls(self, running: bool) -> None:
        state = tk.DISABLED if running else tk.NORMAL
        self.case_list.configure(state=state)
        for button in (self.refresh_button, self.open_case_button, self.validate_button):
            button.configure(state=state)
        self._update_run_button()

    def _update_elapsed(self) -> None:
        if self.running and self.current_case:
            elapsed = int(time.monotonic() - self.started_at)
            self.status_text.set(f"Running {self.current_case} — elapsed {elapsed // 60:02d}:{elapsed % 60:02d}")
        self.root.after(1000, self._update_elapsed)

    def open_last_run(self) -> None:
        if self.last_run_dir is not None:
            os.startfile(self.last_run_dir)

    def open_diagnosis(self) -> None:
        if self.last_run_dir is None:
            return
        path = self.last_run_dir / "diagnosis.txt"
        if path.is_file():
            os.startfile(path)
        else:
            messagebox.showwarning("Diagnosis unavailable", f"No diagnosis file exists at {path}")

    def _close(self) -> None:
        if self.running:
            messagebox.showinfo("Simulation running", "Wait for the current simulation queue to finish before closing.")
            return
        self.root.destroy()


def main() -> None:
    root = tk.Tk()
    SimulationLauncher(root)
    root.mainloop()


if __name__ == "__main__":
    main()
