from __future__ import annotations

from datetime import datetime
from pathlib import Path

import yaml

from batch_runner.run_directories import (
    is_managed_run_snapshot,
    prepare_fresh_run_config,
    prepare_run_config_for_execution,
)


PROJECT_ROOT = Path(__file__).resolve().parents[1]
SOURCE_CASE = PROJECT_ROOT / "cases" / "calcite_quartz_illite_development.yaml"


def _without_output_dir(raw: dict) -> dict:
    data = dict(raw)
    data["paths"] = dict(raw["paths"])
    data["paths"].pop("output_dir", None)
    return data


def test_fresh_run_snapshot_changes_only_output_directory(tmp_path: Path) -> None:
    runs_dir = tmp_path / "runs"
    snapshot = prepare_fresh_run_config(
        SOURCE_CASE,
        runs_dir=runs_dir,
        now=datetime(2026, 8, 19, 19, 30, 45),
    )

    assert snapshot == (
        runs_dir
        / "calcite_quartz_illite_development"
        / "2026-08-19_19-30-45"
        / "run_case.yaml"
    )
    assert snapshot.is_file()
    assert not (snapshot.parent / "results").exists()

    source_raw = yaml.safe_load(SOURCE_CASE.read_text(encoding="utf-8"))
    run_raw = yaml.safe_load(snapshot.read_text(encoding="utf-8"))
    assert _without_output_dir(run_raw) == _without_output_dir(source_raw)
    assert Path(run_raw["paths"]["output_dir"]) == snapshot.parent / "results"

    text = snapshot.read_text(encoding="utf-8")
    assert "Generated by the Reaktoro batch runner" in text
    assert "Scientific settings are unchanged; only paths.output_dir is new" in text


def test_same_timestamp_uses_collision_suffix(tmp_path: Path) -> None:
    runs_dir = tmp_path / "runs"
    now = datetime(2026, 8, 19, 19, 30, 45)

    first = prepare_fresh_run_config(SOURCE_CASE, runs_dir=runs_dir, now=now)
    second = prepare_fresh_run_config(SOURCE_CASE, runs_dir=runs_dir, now=now)

    assert first.parent.name == "2026-08-19_19-30-45"
    assert second.parent.name == "2026-08-19_19-30-45_02"


def test_managed_run_snapshot_is_not_resnapshotted(tmp_path: Path) -> None:
    runs_dir = tmp_path / "runs"
    snapshot = runs_dir / "case-a" / "existing-run" / "run_case.yaml"
    snapshot.parent.mkdir(parents=True)
    snapshot.write_text("paths:\n  output_dir: results\n", encoding="utf-8")

    assert is_managed_run_snapshot(snapshot, runs_dir=runs_dir)
    assert prepare_run_config_for_execution(snapshot, runs_dir=runs_dir) == snapshot.resolve()
    assert not is_managed_run_snapshot(
        tmp_path / "outside" / "run_case.yaml",
        runs_dir=runs_dir,
    )


def test_absolute_output_path_remains_caller_managed(tmp_path: Path) -> None:
    raw = yaml.safe_load(SOURCE_CASE.read_text(encoding="utf-8"))
    raw["paths"]["output_dir"] = str(tmp_path / "explicit-output")
    source = tmp_path / "absolute-output.yaml"
    source.write_text(yaml.safe_dump(raw, sort_keys=False), encoding="utf-8")

    prepared = prepare_run_config_for_execution(source, runs_dir=tmp_path / "runs")

    assert prepared == source.resolve()
    assert not (tmp_path / "runs").exists()
