"""Create immutable case snapshots for fresh direct-run output packages.

The CLI calls this before configuration loading. Relative-output source cases
are validated using a temporary override, then copied beneath ``runs/<case>/<UTC
timestamp>/run_case.yaml`` with only ``paths.output_dir`` changed. Absolute
output paths and already-managed snapshots pass through unchanged for
caller-managed workflows.

This module does not alter scientific settings or overwrite existing packages.
"""

from __future__ import annotations

import copy
import hashlib
import re
import tempfile
from datetime import datetime
from pathlib import Path

import yaml

from batch_runner.config import load_case
from batch_runner.config._base import PROJECT_ROOT


RUNS_DIR = PROJECT_ROOT / "runs"


def prepare_run_config_for_execution(
    case_config: str | Path,
    *,
    runs_dir: str | Path = RUNS_DIR,
    now: datetime | None = None,
    artifact_root: str | Path | None = None,
) -> Path:
    """Return a runnable config path with safe direct-run output semantics.

    Already-managed snapshots and configs with absolute output paths are
    returned unchanged. Other configs are validated and snapshotted by
    :func:`prepare_fresh_run_config`. ``artifact_root`` is used only by DoE
    package launches when validating package-relative scientific dependencies.
    """
    source = Path(case_config).resolve()
    if is_managed_run_snapshot(source, runs_dir=runs_dir):
        return source
    if _configured_output_is_absolute(source):
        return source
    return prepare_fresh_run_config(
        source,
        runs_dir=runs_dir,
        now=now,
        artifact_root=artifact_root,
    )


def is_managed_run_snapshot(
    case_config: str | Path,
    *,
    runs_dir: str | Path = RUNS_DIR,
) -> bool:
    """Return whether *case_config* is ``run_case.yaml`` below *runs_dir*."""
    path = Path(case_config).resolve()
    root = Path(runs_dir).resolve()
    return path.name == "run_case.yaml" and root in path.parents


def prepare_fresh_run_config(
    case_config: str | Path,
    *,
    runs_dir: str | Path = RUNS_DIR,
    now: datetime | None = None,
    artifact_root: str | Path | None = None,
) -> Path:
    """Create and return a timestamped run snapshot.

    The source is first fully loaded with a temporary output override, so an
    invalid case leaves no persistent run directory. Same-second collisions
    use ``_02``, ``_03``, and so on. The generated YAML retains all source
    values except ``paths.output_dir`` and records the source path and SHA-256.

    ``artifact_root`` does not alter persisted YAML. It only tells case loading
    how to resolve package-relative local database/kinetics paths while
    validating a DoE candidate.

    Raises:
        FileNotFoundError: If the source config does not exist.
        ValueError: If the YAML root or required ``paths`` section is invalid.
        RuntimeError: Snapshot construction changed another setting.
        OSError: A run directory or snapshot cannot be created.
        pydantic.ValidationError: The source case is invalid.
    """
    source = Path(case_config).resolve()
    if not source.is_file():
        raise FileNotFoundError(f"case config does not exist: {source}")

    # Validate and resolve the source before creating any persistent run directory.
    with tempfile.TemporaryDirectory(prefix="reaktoro-run-validate-") as temp_dir:
        resolved = load_case(
            source,
            output_dir_override=Path(temp_dir) / "results",
            artifact_root=artifact_root,
        )

    timestamp = (now or datetime.now()).strftime("%Y-%m-%d_%H-%M-%S")
    case_root = Path(runs_dir).resolve() / _safe_name(resolved.config.case.name)
    base = case_root / timestamp
    run_dir = _create_unique_directory(base)
    results_dir = run_dir / "results"

    raw = yaml.safe_load(source.read_text(encoding="utf-8"))
    if not isinstance(raw, dict):
        raise ValueError(f"case config must contain a YAML mapping: {source}")
    generated = copy.deepcopy(raw)
    paths = generated.get("paths")
    if not isinstance(paths, dict):
        raise ValueError("case config must define paths before a run snapshot can be created")

    try:
        output_path = results_dir.relative_to(PROJECT_ROOT.resolve()).as_posix()
    except ValueError:
        output_path = str(results_dir)
    paths["output_dir"] = output_path

    if _without_output_dir(generated) != _without_output_dir(raw):
        raise RuntimeError("run snapshot changed a setting other than paths.output_dir")

    snapshot = run_dir / "run_case.yaml"
    header = (
        "# Generated by the Reaktoro batch runner.\n"
        f"# Source case: {_display_path(source)}\n"
        f"# Source SHA256: {_sha256(source)}\n"
        "# Scientific settings are unchanged; only paths.output_dir is new.\n"
    )
    snapshot.write_text(
        header + yaml.safe_dump(generated, sort_keys=False),
        encoding="utf-8",
    )
    return snapshot


def _configured_output_is_absolute(source: Path) -> bool:
    if not source.is_file():
        return False
    raw = yaml.safe_load(source.read_text(encoding="utf-8"))
    if not isinstance(raw, dict):
        return False
    paths = raw.get("paths")
    if not isinstance(paths, dict):
        return False
    output_dir = paths.get("output_dir")
    return isinstance(output_dir, str) and Path(output_dir).is_absolute()


def _create_unique_directory(base: Path) -> Path:
    suffix = 1
    while True:
        candidate = base if suffix == 1 else base.with_name(f"{base.name}_{suffix:02d}")
        try:
            candidate.mkdir(parents=True, exist_ok=False)
            return candidate
        except FileExistsError:
            suffix += 1


def _without_output_dir(raw: dict) -> dict:
    data = copy.deepcopy(raw)
    paths = data.get("paths")
    if isinstance(paths, dict):
        paths.pop("output_dir", None)
    return data


def _safe_name(value: str) -> str:
    return re.sub(r"[^A-Za-z0-9._-]+", "_", value).strip("._") or "case"


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _display_path(path: Path) -> str:
    try:
        return path.relative_to(PROJECT_ROOT.resolve()).as_posix()
    except ValueError:
        return str(path)
